hello:
    pattern:  /hello/{name}
    defaults: { _controller: JavascriptClassBundle:Hello:index }

jsclass:
    pattern:  /jsclass/{bundle}/{entity}
    defaults: { _controller: JavascriptClassBundle:Entity\Ant:index }

gwah:
    resource: @JavascriptClassBundle/Resources/config/routing2.yml