# http://www.doctrine-project.org/docs/orm/2.0/en/reference/yaml-mapping.html

Nutellove\JavascriptClassBundle\Entity\Anthill:
  type: entity
  table: anthill
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 50
    size:
      type: integer
      default: 10

  oneToMany:
    ants:
      targetEntity: Ant
      mappedBy: anthill

#  oneToOne:
#    address:
#      targetEntity: Address
#      joinColumn:
#        name: address_id
#        referencedColumnName: id
#      cascade: cascadePersist
#  manyToMany:
#    groups:
#      targetEntity: Group
#      joinTable:
#        name: cms_users_groups
#        joinColumns:
#          user_id:
#            referencedColumnName: id
#        inverseJoinColumns:
#          group_id:
#            referencedColumnName: id
#  lifecycleCallbacks:
#    prePersist: [ doStuffOnPrePersist, doOtherStuffOnPrePersistToo ]
#    postPersist: [ doStuffOnPostPersist ]
