
#jsclass_generated:
#    resource: @JavascriptClassBundle/Resources/config/routing/generated_routing.yml

jsclass_entity_load:
    pattern:  /jsclass/{bundleName}/{entityName}/load/{id}
    defaults: { _controller: JavascriptClassBundle:Front:load, _format: json }
